apiVersion: kpack.io/v1alpha2
kind: Builder
metadata:
  name: my-builder
  namespace: build
spec:
  serviceAccountName: kpack-service-account
  tag: procstar/base-cluster-builder
  stack:
    name: base
    kind: ClusterStack
  store:
    name: default
    kind: ClusterStore
  order:
  - group:
    - id: "paketo-buildpacks/go"