apiVersion: kpack.io/v1alpha2
kind: ClusterBuilder
metadata:
  name: base-cluster-builder
spec:
  tag: "index.docker.io/procstar/base-cluster-builderr"
  stack:
    name: base
    kind: ClusterStack
  store:
    name: default
    kind: ClusterStore
  order:
    - group:
        - id: "paketo-buildpacks/java"
    - group:
        - id: "paketo-buildpacks/nodejs"
  serviceAccountRef:
    name: registry-creds
    namespace: build
