apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kpack-build-rolebinding
  namespace: build
subjects:
  - kind: ServiceAccount
    name: registry-creds
    namespace: build
roleRef:
  kind: Role
  name: kpack-build-role
  apiGroup: rbac.authorization.k8s.io
